### ISSUE TITLE
SEO: Double canonical tags an meta tags in header 

### ISSUE THREAD

**Issue by larsroettig** [leerob/leerob.io#261]
![image](https://user-images.githubusercontent.com/5289370/103569533-c5dd3880-4ec7-11eb-98cf-254041a975e6.png)

**Comment by christiankozalla** [comment]
I used leerob.io repo to implement SEO with next-seo on my site (repo: https://github.com/christiankozalla/nextjs-blog)

I noticed the double canonical tags recently due to your issue ;) thanks!

I fixed the double canonical tags by removing `<DefaultSeo />` from `_app.js` because I think default styles are not overriden by other pages' SEO, or at least I don't know how.

In `next-seo` package I found some related issues:
https://github.com/garmeeh/next-seo/issues/610
https://github.com/garmeeh/next-seo/issues/544

So I worked around this by simply using no default SEO, but custom SEO on a per-page-basis`

**Comment by leerob** [comment]
Nice! Thank you 🙏
