### ISSUE TITLE
TypeError: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined

### ISSUE THREAD

**Issue by theindianappguy** [leerob/leerob.io#305]
![Screenshot 2021-04-10 at 8 08 10 AM](https://user-images.githubusercontent.com/55942632/114255881-e55a9480-99d3-11eb-9a53-ec6a1d192de1.png)

I see this as soon as i download and run with 

yarn
yarn dev

**Comment by leerob** [comment]
Hmmm, what version of Node.js are you using?

**Comment by fizerkhan** [comment]
Same error. Node version - v14.15.3

**Comment by haafidz123** [comment]
same problem node - v14.15.3

**Comment by leerob** [comment]
Do you only see this when using next dev? Or is it with next build too?

**Comment by haafidz123** [comment]
![error](https://user-images.githubusercontent.com/59394287/114739459-1855ad00-9d73-11eb-80c8-9d1d3aaf146c.png)
im using yarn dev. and local .env

**Comment by 3rg1s** [comment]
Do we have any fix for this issue yet? I tried to resolve it but didn't manage to get it fixed.

**Comment by jeremycos** [comment]
Hello. I had the same problem. 

It comes from the @lib/google with the crypto library. So I removed the entire @lib/google and all references (with youtube) in index.js. And now it works fine.

**Comment by omaralsoudanii** [comment]
@leerob not sure if this helps or not, but i think the cypher is generated through OpenSSL and between v.14.15.3 to the current LTS version there is a lot of changes in this area ( due to patched OpenSSL vulnerability ).

So maybe it doesn't work because you have the newer version with the patched OpenSSL stuff and the others don't.

Check the [changelogs](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#2020-12-17-version-14153-fermium-lts-bethgriggs)

**Comment by Deep-Codes** [comment]
> Hello. I had the same problem.
> 
> It comes from the @lib/google with the crypto library. So I removed the entire @lib/google and all references (with youtube) in index.js. And now it works fine.

This works tho a lot of work 😅

**Comment by NickCrews** [comment]
I'm pretty sure the problem is that people haven't fully followed the instructions, and they haven't copied `.env.example` into `.env.local` and actually filled in values for `GOOGLE_ENCRYPTION_KEY` and `GOOGLE_ENCRYPTION_IV`. I had this issue, and then filled in these values with `1234`. Then at least the error changed to the thing below, which I assume is "You're not using a valid encryption key, you doofus," which makes sense since. @leerob I bet you could reproduce this if you deleted those entries in your `.env.local`?

I'd imagine the workaround is either

1. Add valid `GOOGLE_ENCRYPTION_*` variables
2. Remove all the offending code as @jeremycos suggests
3. Make things fail more gracefully, so if you don't have valid keys then your youtube API calls etc should return some empty placeholders. I'm trying to do this and plan to submit a PR here.

![image](https://user-images.githubusercontent.com/10820686/122623661-73dd3900-d049-11eb-89da-974303ce2ed2.png)
