### ISSUE TITLE
Consider renaming interfaces

### ISSUE THREAD

**Issue by lavgup** [leerob/leerob.io#370]
As written in the TypeScript style guide, interfaces shouldn't be prefixed with `I`. So e.g. `ISong` should be renamed to `Song`. This is just a naming convention, doesn't matter too much if you prefer prefixing them.

Read [here](https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md#interface).

**Comment by leerob** [comment]
That's not an official style guide though, right? I am curious what the common naming pattern is (I'm a TypeScript novice 😄 )

**Comment by omaralsoudanii** [comment]
Actually that was my thought as well, also why the interfaces if they don't have functions to implement? if they are just to enforce typing I prefer to declare a type rather than interface.

**Comment by leerob** [comment]
Could you expand of the difference, would love to hear your thoughts on how I could improve!

**Comment by omaralsoudanii** [comment]
Sure, the pattern of naming interfaces with `I` usually used in languages like c# or Java. This is due different behaviors between those languages and TS.

In those languages when you define an interface, the interface is just the skeleton of the logic. It has the functions signature, return type, what parameters the function accept etc.. 

The use case is to implement the interface via another class (so you can have multiple classes implementing the same interface each with it's own implementation). 

This is useful because you can enforce the behavior of your app, you use the interface rather than the class that implemented it (concrete class) and if the class didn't implement all the interface functions or didn't conform to what the interface functions declared, then a compile error happens.

Think validation, you can have an interface called `IValidator` and has some functions `validate`, `error`, `sanitize` etc...

Then you would have multiple concrete classes that implements the interface, `EmailValidator`, `PasswordValidator`, `TextValidator`. 

Using [Dependency Injection](https://en.wikipedia.org/wiki/Dependency_injection) you could inject the `IValidator` interface in your libraries and use it's functionality without caring how it's done (from a client standpoint, i.e: I created the interface then you implemented the concrete classes with tests, then I can use the interface to validate email or password).

**Now, none of this applies to TS**, in fact there isn't much difference between interfaces and types. It's just a matter of taste ( unless you have to use one of them, see links below). 

I usually use type alias if I'm gonna use it multiple times and it just has proprieties with their literal types ( like `ISong`, it doesn't have functions and it doesn't need to be extended, it's just there as a type definition to use in libraries, e.g: "This function returns an array of songs" so you put the return type `Song[]`)

This is from the TypeScript on differences:
https://www.typescriptlang.org/docs/handbook/2/objects.html#extending-types

This is how can you utilize interfaces, specially with extending interface from another (less boilerplate, and easier maintenance):
https://www.typescriptlang.org/docs/handbook/2/objects.html#extending-types

**Comment by leerob** [comment]
Thanks for that info. I found this helpful too: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces

Sounds like I should just move to type alises and remove the `I` 😄

**Comment by omaralsoudanii** [comment]
@leerob Lmao this was supposed to be the first link above but for some reason I pasted the other one twice. 

And I said it's a matter of personal style preference, you could use what you feel familiar with and enables you to develop faster rather than following opinionated set of rules. 

Specially when the difference is very small, add to that the tsconfig and how next handles the lint rules.

With time and having a bigger code base I usually refer to the docs and see what I can remove or combine. 

And yeah I am a TypeScript kinda novice too.

What helped me the most is that I have this habit to read what the module does from the codebase in node modules rather than going to the docs, most libraries have a types definitions files.

Proper vscode setup helps a lot even hovering a function or type tells me a lot about how should I implement something.
