### ISSUE TITLE
0Auth github problem !!

### ISSUE THREAD

**Issue by Nouhack** [leerob/leerob.io#634]
Hi , i cloned the portfolio and set my .env file with GITHUB_ID AND GITHUB_SECRET values , but i noticed that in the file page.tsx of guestbook , it always enter the catch , it fails in the Try :

```
  try {
    const [guestbookRes, sessionRes] = await Promise.allSettled([
      getGuestbook(),
      auth(),
    ]);

    if (guestbookRes.status === 'fulfilled' && guestbookRes.value[0]) {
      entries = guestbookRes.value;
    } else {
      console.error(guestbookRes);
    }

    if (sessionRes.status === 'fulfilled') {
      session = sessionRes.value;
    } else {
      console.error(sessionRes);
    }
  } catch (error) {
    console.error(error);
  }
```

i did know that the problem is in the auth layer because when i try to debug with :
```
const promises = [
  getGuestbook().then((res) => {
    console.log("getGuestbook() resolved:", res);
    return res;
  }),
  auth()
    .then((res) => {
      console.log("auth() resolved:", res);
      return res;
    })
    .catch((err) => {
      console.log("Error occurred in auth():", err);
    }),
];

const [guestbookRes, sessionRes] = await Promise.allSettled(promises);
```

it gives me the list of guestbook records but no result when it comes to auth().then

**Comment by z4nr34l** [comment]
This issue exists because of (currenty) lack of stable support for Next.js App Router in `next-auth`. You need to wait for next-auth v5 to get that fixed if I remember well.

You can observe progress of next-auth v5 in this branch: https://github.com/nextauthjs/next-auth/tree/feat/nextjs-auth

That's not issue with this repo. If everything is clear now please close the issue so Lee will not get spammed haha.
