### ISSUE TITLE
Safari Image Layout Shift

### ISSUE THREAD

**Issue by felixhoevelborn** [leerob/leerob.io#694]
I noticed a weird issue when using the latest Safari versions (mobile and desktop). 

The images on `home` have a layout shift when scrolling or clicking / tapping on one of those, which can easily happen.

As this does not happen on Chrome, there must be something about the CSS.

![2024-01-15 um 10 50 52](https://github.com/leerob/leerob.io/assets/90870373/718c27c4-c210-4c61-ba30-07e7df459950)

**Comment by leerob** [comment]
Open to ideas on how to fix it!

**Comment by AdrianFahrbach** [comment]
Just noticed this as well. Crazy how much activity is on this repo 😅

The issue probably has to do with how Safari calculates width on the virtual viewport, so that the layout adjusts its columns on zoom and stays readable. So it is either an a11y feature or a bug 😅
The easy fix for this is to give the container a fixed height (e.g. 496px on desktop) and prevent Safari from recalculating the height. The _correct_ solution would probably be switching to a grid as done in the PR.

**Comment by leerob** [comment]
https://github.com/leerob/leerob.io/pull/698/
